package com.thomsonreuters.pageobjects.utils;


public enum Routing {

    NONE,
    DEFAULT,
    KHSEARCH,
    RESEARCH_DOC_DISPLAY,
    KH_DOC_DISPLAY,
    CAT_PAGES,
    ASK,
    ASK_EDITOR,
    ASK_DEV_WEB_COLLECTION,
    ASK_PROD_WEB_COLLECTION_CATEGORTY_PAGE_CSET,
    ASK_UNRELEASEDCATEGORY,
    OPEN_WEB_SEARCH,
    DOCDISPLAY_UseCollectionSet,
    SPECIFIED_USER_TIMEOUT_3_MINUTES,
	SPECIFIED_USER_TIMEOUT_4_MINUTES,
	SPECIFIED_USER_TIMEOUT_5_MINUTES,
	SPECIFIED_USER_TIMEOUT_7_MINUTES,
    NON_SUBSCRIBER,
    RDD,
    BETA,
	FAST_DRAFT,
	RESEARCH_SEARCH, 
	FIRM_STYLE, 
	FAST_DRAFT_OPEN_WEB,
	FIRM_STYLE_IP_USERS, 
	FIRM_STYLE_IP_USERS_NO_FAC, 
	FAST_DRAFT_IP_USERS, 
	FAST_DRAFT_FIRM_STYLE, 
	FIRM_STYLE_NO_FAC,
    ASSERT_PAGE, 
    FAST_DRAFT_INCORRECT,
    ANNOTATIONS, 
    OPEN_WEB,
    NOWHATSMARKETACCESS,
    WLN_ANNOTATIONS, 
    FOLDERS,
    ANZ_IAC,
    GLOBAL_PAGE,
    SITE_STRUCTURE,
    SITE_STRUCTURE_OW,
    CALENDAR_KEY_DATE_DOC;


}
